import React, { useState } from 'react';
import './BSPReport.css';

const BSPReport = ({ scanResults, imageData }) => {
  const [reportData, setReportData] = useState({
    reportId: `PSR-${Date.now()}`,
    timestamp: new Date().toISOString(),
    location: '',
    reporterName: '',
    reporterContact: '',
    billDescription: '',
    suspicionLevel: 'low'
  });

  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState(null);

  const bspContactInfo = {
    hotline: '(632) 8-708-7087',
    email: 'consumeraffairs@bsp.gov.ph',
    website: 'www.bsp.gov.ph',
    address: 'BSP Complex, A. Mabini Street, Malate, Manila 1004',
    emergencyHotline: '117'
  };

  const handleInputChange = (field, value) => {
    setReportData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const generateReport = async () => {
    setIsGenerating(true);
    
    // Simulate report generation
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const report = {
      ...reportData,
      scanResults,
      authenticityScore: scanResults?.counterfeit_analysis?.authenticity_score || 85,
      detectedFeatures: scanResults?.detections?.length || 0,
      riskLevel: calculateRiskLevel(),
      recommendations: generateRecommendations(),
      bspContactInfo
    };
    
    setGeneratedReport(report);
    setIsGenerating(false);
  };

  const calculateRiskLevel = () => {
    if (!scanResults?.counterfeit_analysis) return 'Unknown';
    
    const score = scanResults.counterfeit_analysis.authenticity_score;
    if (score >= 90) return 'Low Risk';
    if (score >= 70) return 'Medium Risk';
    if (score >= 50) return 'High Risk';
    return 'Critical Risk';
  };

  const generateRecommendations = () => {
    const score = scanResults?.counterfeit_analysis?.authenticity_score || 85;
    
    if (score >= 90) {
      return [
        'Banknote appears authentic based on AI analysis',
        'Continue with normal transaction procedures',
        'Consider additional verification if suspicious'
      ];
    } else if (score >= 70) {
      return [
        'Banknote shows some irregularities - exercise caution',
        'Verify with additional authentication methods',
        'Contact BSP if concerns persist'
      ];
    } else {
      return [
        'Banknote shows significant authenticity concerns',
        'Do not accept - potential counterfeit detected',
        'Report immediately to BSP and local authorities',
        'Preserve banknote as evidence if safe to do so'
      ];
    }
  };

  const downloadReport = () => {
    const reportContent = generateReportContent();
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `BSP_Report_${reportData.reportId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateReportContent = () => {
    return `
BANGKO SENTRAL NG PILIPINAS
COUNTERFEIT CURRENCY REPORT

Report ID: ${generatedReport.reportId}
Date: ${new Date(generatedReport.timestamp).toLocaleString()}

=== REPORTER INFORMATION ===
Name: ${generatedReport.reporterName || 'Not provided'}
Contact: ${generatedReport.reporterContact || 'Not provided'}
Location: ${generatedReport.location || 'Not provided'}

=== BANKNOTE ANALYSIS ===
AI Authenticity Score: ${generatedReport.authenticityScore}%
Risk Level: ${generatedReport.riskLevel}
Features Detected: ${generatedReport.detectedFeatures}
Suspicion Level: ${generatedReport.suspicionLevel.toUpperCase()}

Description: ${generatedReport.billDescription || 'No description provided'}

=== RECOMMENDATIONS ===
${generatedReport.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

=== BSP CONTACT INFORMATION ===
Hotline: ${bspContactInfo.hotline}
Email: ${bspContactInfo.email}
Website: ${bspContactInfo.website}
Address: ${bspContactInfo.address}
Emergency Hotline: ${bspContactInfo.emergencyHotline}

=== TECHNICAL DETAILS ===
Generated by: PesoScan AI Detection System
Model Version: YOLOv8 Counterfeit Detection v2.0
Processing Time: ${new Date().toISOString()}

Note: This report is generated by an AI system for preliminary assessment.
Official verification should be conducted by BSP-authorized personnel.
    `.trim();
  };

  return (
    <div className="bsp-report">
      <div className="bsp-header">
        <div className="bsp-logo">
          <svg width="40" height="40" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 2L2 7l10 5 10-5-10-5z" stroke="currentColor" strokeWidth="2" fill="none"/>
            <path d="M2 17l10 5 10-5" stroke="currentColor" strokeWidth="2" fill="none"/>
            <path d="M2 12l10 5 10-5" stroke="currentColor" strokeWidth="2" fill="none"/>
          </svg>
        </div>
        <div className="bsp-title">
          <h2>BSP Counterfeit Report</h2>
          <p>Official Bangko Sentral ng Pilipinas Reporting System</p>
        </div>
      </div>

      {!generatedReport ? (
        <div className="report-form">
          <div className="form-section">
            <h3>Report Information</h3>
            <div className="form-grid">
              <div className="form-group">
                <label>Reporter Name</label>
                <input
                  type="text"
                  value={reportData.reporterName}
                  onChange={(e) => handleInputChange('reporterName', e.target.value)}
                  placeholder="Your full name"
                />
              </div>
              
              <div className="form-group">
                <label>Contact Information</label>
                <input
                  type="text"
                  value={reportData.reporterContact}
                  onChange={(e) => handleInputChange('reporterContact', e.target.value)}
                  placeholder="Phone number or email"
                />
              </div>
              
              <div className="form-group">
                <label>Location</label>
                <input
                  type="text"
                  value={reportData.location}
                  onChange={(e) => handleInputChange('location', e.target.value)}
                  placeholder="Where was the banknote encountered?"
                />
              </div>
              
              <div className="form-group">
                <label>Banknote Description</label>
                <select
                  value={reportData.suspicionLevel}
                  onChange={(e) => handleInputChange('suspicionLevel', e.target.value)}
                >
                  <option value="low">Low - Minor concerns</option>
                  <option value="medium">Medium - Notable irregularities</option>
                  <option value="high">High - Strong suspicion</option>
                  <option value="critical">Critical - Likely counterfeit</option>
                </select>
              </div>
            </div>
            
            <div className="form-group full-width">
              <label>Bill Description</label>
              <textarea
                value={reportData.billDescription}
                onChange={(e) => handleInputChange('billDescription', e.target.value)}
                placeholder="Describe any suspicious characteristics, where you received it, etc."
                rows="4"
              />
            </div>
          </div>

          <div className="scan-summary">
            <h3>AI Analysis Summary</h3>
            <div className="summary-grid">
              <div className="summary-item">
                <span className="summary-label">Authenticity Score</span>
                <span className="summary-value">
                  {scanResults?.counterfeit_analysis?.authenticity_score || 85}%
                </span>
              </div>
              <div className="summary-item">
                <span className="summary-label">Features Detected</span>
                <span className="summary-value">
                  {scanResults?.detections?.length || 0}
                </span>
              </div>
              <div className="summary-item">
                <span className="summary-label">Risk Level</span>
                <span className={`summary-value risk-${calculateRiskLevel().toLowerCase().replace(' ', '-')}`}>
                  {calculateRiskLevel()}
                </span>
              </div>
            </div>
          </div>

          <button 
            className="generate-report-btn"
            onClick={generateReport}
            disabled={isGenerating}
          >
            {isGenerating ? (
              <>
                <div className="spinner"></div>
                Generating Report...
              </>
            ) : (
              <>
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" stroke="currentColor" strokeWidth="2"/>
                  <polyline points="14,2 14,8 20,8" stroke="currentColor" strokeWidth="2"/>
                  <line x1="16" y1="13" x2="8" y2="13" stroke="currentColor" strokeWidth="2"/>
                  <line x1="16" y1="17" x2="8" y2="17" stroke="currentColor" strokeWidth="2"/>
                </svg>
                Generate BSP Report
              </>
            )}
          </button>
        </div>
      ) : (
        <div className="generated-report">
          <div className="report-header">
            <h3>Report Generated Successfully</h3>
            <div className="report-id">Report ID: {generatedReport.reportId}</div>
          </div>

          <div className="report-content">
            <div className="report-section">
              <h4>Analysis Results</h4>
              <div className="results-grid">
                <div className="result-item">
                  <span className="result-label">Authenticity Score</span>
                  <span className="result-value authenticity">
                    {generatedReport.authenticityScore}%
                  </span>
                </div>
                <div className="result-item">
                  <span className="result-label">Risk Assessment</span>
                  <span className={`result-value risk-${generatedReport.riskLevel.toLowerCase().replace(' ', '-')}`}>
                    {generatedReport.riskLevel}
                  </span>
                </div>
              </div>
            </div>

            <div className="report-section">
              <h4>Recommendations</h4>
              <ul className="recommendations-list">
                {generatedReport.recommendations.map((rec, index) => (
                  <li key={index}>{rec}</li>
                ))}
              </ul>
            </div>
          </div>

          <div className="report-actions">
            <button className="download-btn" onClick={downloadReport}>
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" stroke="currentColor" strokeWidth="2"/>
                <polyline points="7,10 12,15 17,10" stroke="currentColor" strokeWidth="2"/>
                <line x1="12" y1="15" x2="12" y2="3" stroke="currentColor" strokeWidth="2"/>
              </svg>
              Download Report
            </button>
          </div>
        </div>
      )}

      <div className="bsp-contact-info">
        <h3>BSP Contact Information</h3>
        <div className="contact-grid">
          <div className="contact-item">
            <span className="contact-label">Hotline</span>
            <span className="contact-value">{bspContactInfo.hotline}</span>
          </div>
          <div className="contact-item">
            <span className="contact-label">Email</span>
            <span className="contact-value">{bspContactInfo.email}</span>
          </div>
          <div className="contact-item">
            <span className="contact-label">Website</span>
            <span className="contact-value">{bspContactInfo.website}</span>
          </div>
          <div className="contact-item">
            <span className="contact-label">Emergency</span>
            <span className="contact-value">{bspContactInfo.emergencyHotline}</span>
          </div>
        </div>
        <div className="contact-address">
          <strong>Address:</strong> {bspContactInfo.address}
        </div>
      </div>
    </div>
  );
};

export default BSPReport;